### ISSUE TITLE
db_r50_icdar15.yaml 文件内容变动导致用例报错

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#128]
关联位置：https://github.com/mindspore-lab/mindocr/blob/main/configs/det/dbnet/db_r50_icdar15.yaml
whl版本：mindocr/version/202303/20230320
源码：2023/3/27 main分支

具体问题：db_r50_icdar15.yaml 文件内容变动导致用例报错，主要变动内容有dataset_root: /Users/Samit/Data/datasets 更新为 dataset_root: /data/ocr_datasets
把内容变动的pr  评论在下方即可

**Comment by HaoyangLee** [comment]
https://github.com/mindspore-lab/mindocr/pull/127

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
