### ISSUE TITLE
crnn_vgg7.yaml 单卡eval精度为78.22 远小于readme的82.03

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#135]
关联位置：https://github.com/mindspore-lab/mindocr/blob/main/configs/rec/crnn/crnn_vgg7.yaml
源码：2023/3/31 main分支
mindcv whl版本：2023/3/29 源码安装
Describe the expected behavior / 预期结果 (Mandatory / 必填)
crnn_vgg7.yaml 单卡eval精度应该在【82.03-0.5，82.03+0.5】
复现命令示例：python /data3/cty/mind_lab/test_mindocr/mindocr/tools/eval.py -c /data3/cty/mind_lab/test_mindocr/mindocr_models_test_data/crnn_vgg7/test_eval_crnn_vgg7_ascend_icdar15_1p_graph_001/crnn_vgg7.yaml > case.log 2>&1

**Comment by hqkate** [comment]
您好，請問是用單卡跑 [configs/rec/crnn/crnn_vgg7.yaml](https://github.com/mindspore-lab/mindocr/blob/main/configs/rec/crnn/crnn_vgg7.yaml) 配置訓練，然後訓練好的模型跑 eval，精度是78%嗎？
如果是這樣的話，因為原來的模型是用8卡去跑的，單卡跑的話需要把batch size調到原來的8倍，即48，以確保全局batch size一致。
注意，因為卡的數量發生了變化，有可能精度會受影響。

**Comment by tacyi** [comment]
在welink 已经进一步描述了问题的细节

**Comment by hqkate** [comment]
同 #137

**Comment by SamitHuang** [comment]
单卡训练时，global batch_size会小变导致精度变低。 在这预期之中，需要调batch_size。

**Comment by SamitHuang** [comment]
已在https://github.com/mindspore-lab/mindocr/pull/156 文档中强调说明。

**Comment by HaoyangLee** [comment]
相关PR https://github.com/mindspore-lab/mindocr/pull/164
文档已说明模型各种运行模式下的参数配置情况。

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
