### ISSUE TITLE
crnn_vgg7.yaml 单卡train报错

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#136]
关联位置：https://github.com/mindspore-lab/mindocr/blob/main/configs/rec/crnn/crnn_vgg7.yaml
源码：2023/3/31 main分支
mindcv whl版本：2023/3/29 源码安装
Describe the expected behavior / 预期结果 (Mandatory / 必填)
crnn_vgg7.yaml 单卡train 正常
复现命令示例： python /data3/cty/mind_lab/test_mindocr/mindocr/tools/train.py -c /data3/cty/mind_lab/test_mindocr/mindocr_models_test_data/crnn_vgg7/test_train_crnn_vgg7_ascend_icdar15_1p_graph_005/crnn_vgg7.yaml > case.log 2>&1
具体报错：
INFO: The character_dict_path is None, model can only recognize number and lower letters
==> Dataset output columns:
         ['image', 'text_seq']
INFO: The character_dict_path is None, model can only recognize number and lower letters
Traceback (most recent call last):
  File "/data3/cty/mind_lab/test_mindocr/mindocr/tools/train.py", line 182, in <module>
    main(config)
  File "/data3/cty/mind_lab/test_mindocr/mindocr/tools/train.py", line 72, in main
    loader_eval = build_dataset(
  File "/data3/cty/mind_lab/test_mindocr/mindocr/mindocr/data/builder.py", line 105, in build_dataset
    dataset = dataset_class(**dataset_args)
  File "/data3/cty/mind_lab/test_mindocr/mindocr/mindocr/data/rec_lmdb_dataset.py", line 68, in __init__
    _data = self.data_idx_order_list[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

Additional context / 备注 (Optional / 选填)
crnn_vgg7.yaml又被更新了，可以从yaml看到以前数据集是icdar15,现在改成了data_lmdb_release，是不是这个导致? 更新代码请严格把控质量

**Comment by hqkate** [comment]
您好，“IndexError: index 0 is out of bounds for axis 0 with size 0“ 這個報錯大概率是因為數據集路徑設置不正確，請問可以貼一下config裡面數據集路徑以及您本地數據集的結構嗎，謝謝！

**Comment by tacyi** [comment]
在welink 已经进一步描述了问题的细节

**Comment by hqkate** [comment]
您好，根據您在welink上面的config文件，關於eval的數據集的路徑設置可能有問題：

<img width="286" alt="捕获" src="https://user-images.githubusercontent.com/26082447/229329189-82a64f8b-dd2a-4b2d-aafd-f6856daf59f6.PNG">

根據您welink的顯示，validation/ 數據集應該是在 data_lmdb_release/底下，但config的路徑確實設置了 /data1/mindspore_dataset/validation/ 請您更新路徑無誤后在試一下，謝謝！

**Comment by HaoyangLee** [comment]
相关PR https://github.com/mindspore-lab/mindocr/pull/164
文档已说明模型各种运行模式下的参数配置情况。

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
