### ISSUE TITLE
crnn_resnet34.yaml单卡train报错

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#138]
关联位置：https://github.com/mindspore-lab/mindocr/blob/main/configs/rec/crnn/crnn_resnet34.yaml
源码：2023/3/31 main分支
mindcv whl版本：2023/3/29 源码安装
Describe the expected behavior / 预期结果 (Mandatory / 必填)
crnn_resnet34.yaml单卡train 正常
复现命令示例： python /data3/cty/mind_lab/test_mindocr/mindocr/tools/train.py -c /data3/cty/mind_lab/test_mindocr/mindocr_models_test_data/crnn_resnet34/test_train_crnn_resnet34_ascend_data_lmdb_release_1p_graph_005/crnn_resnet34.yaml > case.log 2>&1
具体报错：
INFO: The character_dict_path is None, model can only recognize number and lower letters
==> Dataset output columns:
         ['image', 'text_seq']
INFO: The character_dict_path is None, model can only recognize number and lower letters
Traceback (most recent call last):
  File "/data3/cty/mind_lab/test_mindocr/mindocr/tools/train.py", line 182, in <module>
    main(config)
  File "/data3/cty/mind_lab/test_mindocr/mindocr/tools/train.py", line 72, in main
    loader_eval = build_dataset(
  File "/data3/cty/mind_lab/test_mindocr/mindocr/mindocr/data/builder.py", line 105, in build_dataset
    dataset = dataset_class(**dataset_args)
  File "/data3/cty/mind_lab/test_mindocr/mindocr/mindocr/data/rec_lmdb_dataset.py", line 68, in __init__
    _data = self.data_idx_order_list[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

Additional context / 备注 (Optional / 选填)
严格把控代码更新质量，不要随意更新配置名称等，会导致用例全部得重新检查和修改

**Comment by hqkate** [comment]
您好，與 #136 類似，應該是數據集設置的問題。

**Comment by tacyi** [comment]
在welink 已经进一步描述

**Comment by HaoyangLee** [comment]
相关PR #164 
文档已说明模型各种运行模式下的参数配置情况。

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
