### ISSUE TITLE
安装whl包与源码里面的导入不一致

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#141]
源码：2023/3/31 main分支
mindocr whl版本：2023/3/29 源码安装
Describe the expected behavior / 预期结果 (Mandatory / 必填)
安装whl包 如何地方都可正常导入，与与源码里面的导入方式一致
具体报错：
root@10-90-53-131:test_mindocr# pytest PyTest/testcase/mindocr/interfaces/test_build_model.py
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.7.5, pytest-7.2.0, pluggy-1.0.0
rootdir: /data3/cty/mind_lab/test_mindocr
collected 0 items / 1 error

=============================================================================================== ERRORS ================================================================================================
_______________________________________________________________ ERROR collecting PyTest/testcase/mindocr/interfaces/test_build_model.py _______________________________________________________________
ImportError while importing test module '/data3/cty/mind_lab/test_mindocr/PyTest/testcase/mindocr/interfaces/test_build_model.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/root/archiconda3/envs/model_zoo_r2.0.0/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
PyTest/testcase/mindocr/interfaces/test_build_model.py:13: in <module>
    from mindocr.data import build_dataset
E   ModuleNotFoundError: No module named 'mindocr.data'

Additional context / 备注 (Optional / 选填)
开发简要描述：包叫做mindocr，而mindocr下面还有个mindocr的目录导致的，即代码在mindocr/mindocr下面。
所以mindocr包安装之后，正确的导入方式是from mindocr.mindocr import xxx。要想改为去掉一层mindocr，需要学习paddleocr，修改mindocr目录，__init__.py文件，mindocr.py

**Comment by HaoyangLee** [comment]
Fixed. PR https://github.com/mindspore-lab/mindocr/pull/161 https://github.com/mindspore-lab/mindocr/pull/159 https://github.com/mindspore-lab/mindocr/pull/147

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
