### ISSUE TITLE
list_models 接口的返回值源码逻辑有改动

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#194]
list_models 接口的返回值源码逻辑有改动，请把变动pr评论出来解单
1：@pytest.mark.level('level0')
    def test_list_models_001():
        '''
        all_models test
        '''
        all_models = mindocr.list_models()
>       assert all_models == ['crnn_r34', 'crnn_vgg7', 'dbnet_r50']
E       AssertionError: assert ['crnn_resnet...net_resnet50'] == ['crnn_r34', ..., 'dbnet_r50']
E         At index 0 diff: 'crnn_resnet34' != 'crnn_r34'
E         Use -v to get more diff

2：  @pytest.mark.level('level0')
    def test_list_models_002(pretrained=True):
        '''
        pretrained test
        '''
        pretrained_models = mindocr.list_models(pretrained=pretrained)
>       assert pretrained_models == ['crnn_r34', 'crnn_vgg7', 'dbnet_r50']
E       AssertionError: assert ['crnn_resnet...net_resnet50'] == ['crnn_r34', ..., 'dbnet_r50']
E         At index 0 diff: 'crnn_resnet34' != 'crnn_r34'
E         Use -v to get more diff

PyTest/testcase/mindocr/interfaces/test_list_models.py:21: AssertionError

3： @pytest.mark.level('level0')
    def test_list_models_003(filter_name='cr*'):
        '''
        filter_name test
        '''
        filter_models = mindocr.list_models(filter=filter_name)
>       assert filter_models == ['crnn_r34', 'crnn_vgg7']
E       AssertionError: assert ['crnn_resnet34', 'crnn_vgg7'] == ['crnn_r34', 'crnn_vgg7']
E         At index 0 diff: 'crnn_resnet34' != 'crnn_r34'
E         Use -v to get more diff

4： @pytest.mark.level('level0')
    def test_list_models_004(module='det_dbnet'):
        '''
        module test
        '''
        module_models = mindocr.list_models(module=module)
>       assert module_models == ['dbnet_r50']
E       AssertionError: assert ['dbnet_resnet50'] == ['dbnet_r50']
E         At index 0 diff: 'dbnet_resnet50' != 'dbnet_r50'
E         Use -v to get more diff

5： @pytest.mark.level('level0')
    def test_list_models_005(exclude_filters='crnn*'):
        '''
        exclude_filters test
        '''
        exclude_filters_models = mindocr.list_models(exclude_filters=exclude_filters)
>       assert exclude_filters_models == ['dbnet_r50']
E       AssertionError: assert ['dbnet_resnet50'] == ['dbnet_r50']
E         At index 0 diff: 'dbnet_resnet50' != 'dbnet_r50'
E         Use -v to get more diff

**Comment by SamitHuang** [comment]
https://github.com/mindspore-lab/mindocr/pull/184

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
