### ISSUE TITLE
[630][Model] CRNN中文数据集支持，中英文混合训练

### ISSUE THREAD

**Issue by HaoyangLee** [mindspore-lab/mindocr#221]

**Comment by panshaowu** [comment]
CRNN已支持中文数据集，配置文件[`configs/rec/crnn/crnn_resnet34_ch.yaml`](https://github.com/mindspore-lab/mindocr/blob/main/configs/rec/crnn/crnn_resnet34_ch.yaml)，字典文件`ch_dict.txt`覆盖了繁简体中文、数字、常用符号以及大小写的英文字母。RFC关闭。
