### ISSUE TITLE
[630][FCENet] FCENet模型支持

### ISSUE THREAD

**Issue by HaoyangLee** [mindspore-lab/mindocr#228]

**Comment by 6098669** [comment]
请问FCENet的CTW1500和Totaltext数据集的结果什么时候公布呢，有mmocr和paddleocr复现的精度高吗，我用mmocr和paddleocr复现的精度均未达到论文中的精度。

**Comment by zhtmike** [comment]
> 请问FCENet的CTW1500和Totaltext数据集的结果什么时候公布呢，有mmocr和paddleocr复现的精度高吗，我用mmocr和paddleocr复现的精度均未达到论文中的精度。

@SamitHuang

**Comment by kk928290341** [comment]
#369
