### ISSUE TITLE
requirements.txt 中的包 packaging需要加上版本号限制

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#470]
10:37:13  mindspore-gpu 1.9.0 requires packaging>=20.0, but you have packaging 14.0 which is incompatible.

我这边复现 packaging==23.1这个版本可行

请把 packaging加上版本号限制，更新requirements.txt

**Comment by panshaowu** [comment]
感谢您的反馈。项目开发人员已经参考您的建议，调整了`requirements.txt`中的版本约束。
如果新建虚拟环境后，直接执行`python -m pip install -r requirements.txt`，当前版本将默认安装packaging 23.2。
我们在部分环境中测试，packaging 22.0和21.0亦可满足依赖条件。
