### ISSUE TITLE
ABINet部分算子需适配mindspore 2.0

### ISSUE THREAD

**Issue by HaoyangLee** [mindspore-lab/mindocr#491]
https://github.com/mindspore-lab/mindocr/blob/main/mindocr/models/utils/abinet_layers.py#L9
https://github.com/mindspore-lab/mindocr/blob/main/mindocr/models/utils/abinet_layers.py#L15
使用的校验接口部分已弃用，请修改一下，确保在mindspore2.0可以跑通。可参考https://github.com/mindspore-lab/mindocr/pull/169

**Comment by horcham** [comment]
当前ABINet已可在ms2.2下跑通训练与推理。

**Comment by panshaowu** [comment]
ABINet网络开发需求已完成，在MindSpore r2.2.x环境下复验可正常运行，Issue关闭。
