### ISSUE TITLE
多机多卡无限等待bug

### ISSUE THREAD

**Issue by jiangxiluning** [mindspore-lab/mindocr#582]
https://github.com/mindspore-lab/mindocr/blob/3d26c69bb23d7cca8abe62617fba8d0bbbbbff32/tools/modelarts_adapter/modelarts.py#L70C34-L70C38

多机多卡情况下，rank不是从0开始的。建议改为 local_rank % 8 == 0

**Comment by panshaowu** [comment]
@jiangxiluning 您好，感谢您的反馈和建议。
该问题已在PR#671中修复。
