### ISSUE TITLE
No such file or directory: 'mindocr/utils/dict/ch_dict.txt'

### ISSUE THREAD

**Issue by shirwy** [mindspore-lab/mindocr#585]
python mindocr/tools/infer/text/predict_rec.py

No such file or directory: 'mindocr/utils/dict/ch_dict.txt'

**Comment by panshaowu** [comment]
Thanks for your feedback.
It seems that this bug has been fixed.
Please refer to [MindOCR Online Inference](https://github.com/mindspore-lab/mindocr/blob/main/tools/infer/text/README.md) to get more details on using this script.

Test Result:
``` text

```
