### ISSUE TITLE
【需求】支持自定义配置，自定义字典的预测

### ISSUE THREAD

**Issue by panxua** [mindspore-lab/mindocr#611]
当前推理的网络构建使用如下接口
https://github.com/mindspore-lab/mindocr/blob/25bd212875bf5035c0ac3b015181cab4ee6276f0/tools/infer/text/predict_rec.py#L80
貌似仅支持硬编码的如下配置
https://github.com/mindspore-lab/mindocr/blob/25bd212875bf5035c0ac3b015181cab4ee6276f0/tools/infer/text/predict_rec.py#L32C1-L38C2
自定义字典，改变输出序列长度后不能使用该脚本推理，能否提供支持自定义配置的接口以及指导。

**Comment by Bourn3z** [comment]
本问题已由 #648 解决 ，现在可以通过`tools/infer/text/predict_from_yaml.py`脚本完成自定义的推理，具体说明请看文档`tools/infer/text/README.MD`。

**Comment by panshaowu** [comment]
@panxua 您好，感谢您的问题反馈。自定义字典功能已开发支持，本issue将暂时关闭，如有进一步的问题或需求，请与我们联系。
