### ISSUE TITLE
E39999: Inner Error, Please contact support engineer!

### ISSUE THREAD

**Issue by qulishen** [mindspore-lab/mindocr#615]
[ERROR] DEVICE(2420702,fffe06ffd1e0,python):2023-11-20-15:34:32.886.561 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:761] DumpTaskExceptionInfo] Task fail infos task_id: 2, stream_id: 45, tid: 2420702, device_id: 0, retcode: 507011 ( model execute failed)
[ERROR] DEVICE(2420702,fffe06ffd1e0,python):2023-11-20-15:34:32.887.652 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:770] DumpTaskExceptionInfo] Dump node (Default/GetNext-op18) task error input/output data to: ./rank_0/node_dump
The function call stack:
In file /home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/train/dataset_helper.py:106/        outputs = self.get_next()/

[WARNING] DEVICE(2420702,fffe06ffd1e0,python):2023-11-20-15:34:32.887.680 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:777] DumpTaskExceptionInfo] GetNext error may be caused by slow data processing (bigger than 20s / batch) or transfer data to device error.
[WARNING] DEVICE(2420702,fffe06ffd1e0,python):2023-11-20-15:34:32.887.695 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:779] DumpTaskExceptionInfo] Suggestion: 
[WARNING] DEVICE(2420702,fffe06ffd1e0,python):2023-11-20-15:34:32.887.710 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:780] DumpTaskExceptionInfo]     1) Set the parameter dataset_sink_mode=False of model.train(...) or model.eval(...) and try again.
[WARNING] DEVICE(2420702,fffe06ffd1e0,python):2023-11-20-15:34:32.887.724 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:782] DumpTaskExceptionInfo]     2) Reduce the batch_size in data processing and try again.
[WARNING] DEVICE(2420702,fffe06ffd1e0,python):2023-11-20-15:34:32.887.738 [mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:783] DumpTaskExceptionInfo]     3) You can create iterator by interface create_dict_iterator() of dataset class to independently verify the performance of data processing without training. Refer to the link for data processing optimization suggestions: https://mindspore.cn/tutorials/experts/zh-CN/r1.10/dataset/optimize.html
Traceback (most recent call last):
  File "eval.py", line 66, in <module>
    crnn_eval()
  File "/home/ma-user/work/qls/models-r110/official/cv/crnn/src/model_utils/moxing_adapter.py", line 113, in wrapped_func
    run_func(*args, **kwargs)
  File "eval.py", line 62, in crnn_eval
    res = model.eval(dataset, dataset_sink_mode=config.device_target == 'Ascend')
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/train/model.py", line 1430, in eval
    eval_result = self._eval_dataset_sink_process(valid_dataset, list_callback, cb_params)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/train/model.py", line 1291, in _eval_dataset_sink_process
    outputs = eval_network(*inputs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 619, in __call__
    out = self.compile_and_run(*args)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 1008, in compile_and_run
    return _cell_graph_executor(self, *new_inputs, phase=self.phase)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 1192, in __call__
    return self.run(obj, *args, phase=phase)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 1229, in run
    return self._exec_pip(obj, *args, phase=phase_real)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 98, in wrapper
    results = fn(*arg, **kwargs)
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 1211, in _exec_pip
    return self._graph_executor(args, phase)
RuntimeError: Run task error!

----------------------------------------------------
- Ascend Error Message:
----------------------------------------------------
E39999: Inner Error, Please contact support engineer!
E39999  Aicpu kernel execute failed, device_id=0, stream_id=45, task_id=2.[FUNC:PrintAicpuErrorInfo][FILE:task.cc][LINE:774]
        TraceBack (most recent call last):
        Aicpu kernel execute failed, device_id=0, stream_id=45, task_id=2, fault op_name=[FUNC:GetError][FILE:stream.cc][LINE:1044]
        rtStreamSynchronize execute failed, reason=[the model stream execute failed][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:49]

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/plugin/device/ascend/hal/hardware/ascend_graph_executor.cc:214 RunGraph

[WARNING] MD(2420702,ffffae3f1a40,python):2023-11-20-15:34:32.897.650 [mindspore/ccsrc/minddata/dataset/engine/datasetops/data_queue_op.cc:93] ~DataQueueOp] preprocess_batch: 209; batch_queue: 0, 0, 0, 0, 0, 0, 0, 0, 0, 16; push_start_time: 2023-11-20-15:33:55.263.583, 2023-11-20-15:33:55.264.156, 2023-11-20-15:33:55.264.782, 2023-11-20-15:33:55.265.363, 2023-11-20-15:33:55.265.890, 2023-11-20-15:33:55.266.425, 2023-11-20-15:33:55.266.962, 2023-11-20-15:33:55.267.601, 2023-11-20-15:33:55.268.272, 2023-11-20-15:33:55.268.822; push_end_time: 2023-11-20-15:33:55.263.674, 2023-11-20-15:33:55.264.270, 2023-11-20-15:33:55.264.868, 2023-11-20-15:33:55.265.449, 2023-11-20-15:33:55.265.971, 2023-11-20-15:33:55.266.518, 2023-11-20-15:33:55.267.049, 2023-11-20-15:33:55.267.687, 2023-11-20-15:33:55.268.359, 2023-11-20-15:33:55.670.409.

**Comment by panshaowu** [comment]
Thanks for your feedback.
It seems that something went wrong in MindSpore r1.10.
Please try to use MindSpore r2.2.11, which is more stable. CRNN has been well tested on this MindSpore version.

**Comment by panshaowu** [comment]
@qulishen 
As far as we know, this problem is due to failure of executing an AICPU operator, which is mostly caused by installing a wrong version of CANN. (Refer to [MindSpore Error Analysis](https://www.mindspore.cn/tutorials/zh-CN/r2.2/advanced/error_analysis/error_scenario_analysis.html))
This Issue will be closed temporarily. If you need further help, please contact us again.
