### ISSUE TITLE
model.pretrained和model.backbone.pretrained同时生效，在多个yaml文件中需要修改

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#619]
如在这些yaml文件中
db_r18_ctw1500.yaml
db_r18_mlt2017.yaml
db_r18_td500.yaml
db_r18_totaltext.yaml

db_r50_ctw1500.yaml
db_r50_mlt2017.yaml
db_r50_td500.yaml
db_r50_totaltext.yaml

当model.pretrained存在时，model.backbone.pretrained应该为False，否则会有冗余逻辑。

**Comment by panshaowu** [comment]
已在[PR618](https://github.com/mindspore-lab/mindocr/pull/618)中修复。
