### ISSUE TITLE
How to do only text detection on minidocr?

### ISSUE THREAD

**Issue by R4Ajeti** [mindspore-lab/mindocr#691]
How do I do only text detection on minidocr using models from here:
https://github.com/mindspore-lab/mindocr/blob/main/configs/det/dbnet/README.md
-> section 3. Results -> DBNet and DBNet++ were trained on the ICDAR2015, MSRA-TD500, SCUT-CTW1500, Total-Text, and MLT2017 datasets ...

Let for example I want text detection speed and accuracy of this one on my dataset (images folder):
MLT2017 | DBNet | D910x8-MS2.0-G | ResNet-18 | SynthText that has throughput = 344.8 img/s

Any example any help is appreciated.

BTW: What does "Throughput" mean exactly? In this contest, I mean in terms of what machine those stats are available.

EDITED: 1. Also why is the box detection per each word individual instead of being the same bounding box when all words are in the same line as it is on paddleocr? Is there any easy way I can archive it?
2. This code is working to detect and recognize but is very slow (0.9 seconds to detect a single image 1152x104px on macbook pro m3) I need a faster one with lower accuracy trade off and separated detection from recognition:
```
python tools/infer/text/predict_system.py --image_dir deploy/py_infer/images \
                                          --det_algorithm DB++  \
                                          --rec_algorithm CRNN
```

**Comment by horcham** [comment]
Hello, for only detection, you can run 
```bash
python tools/infer/text/predict_det.py  --image_dir {path_to_img or dir_to_imgs} --det_algorithm DB++
```
please refer to https://github.com/mindspore-lab/mindocr/blob/main/tools/infer/text/README.md for more details.

The F-score and throughput are available on 8xAscend 910 with mindspore 2.0.
