### ISSUE TITLE
[Model] Update TableMasterHead

### ISSUE THREAD

**Issue by hongziqi** [mindspore-lab/mindocr#745]
### This issue is focused on updating the TableMasterHead network in MindOCR(mindspore==2.3.1)

**1. Inference Results Comparison**
Original Network (TableMasterHead)
The inference results of the original TableMasterHead show the following characteristics:
a. pubtabnet/train/PMC514525_002_01.png result:
![image](https://github.com/user-attachments/assets/f6748021-0cfd-451f-b7f7-985c35505c52)

b. other example:
![image](https://github.com/user-attachments/assets/dded2eed-a9c7-4925-860f-858f7a07d244)

Modified Network (Updated TableMasterHead)
After modifications, the new TableMasterHead network demonstrates improved results:
a. pubtabnet/train/PMC514525_002_01.png result:
![image](https://github.com/user-attachments/assets/d315c0d4-cbb5-4445-ae45-de118361dbdd)

b. other example:
![image](https://github.com/user-attachments/assets/7f5ff626-71d5-45a4-9ea4-d5291a25d1f5)

**2. Validation Accuracy Comparison**
Original Network Validation Accuracy:
The original network achieved an accuracy of 77.43% on the validation  PubTabNet dataset.

Modified Network Validation Accuracy:
After the updates, the modified network achieved an improved validation accuracy of  77.49%  on the same dataset.
[table_master_eval_mode_0.log](https://github.com/user-attachments/files/17289452/table_master_eval_mode_0.log)
[table_master_eval_mode_1.log](https://github.com/user-attachments/files/17289456/table_master_eval_mode_1.log)

**Comment by tonytonglt** [comment]
Solved by [https://github.com/mindspore-lab/mindocr/pull/746](url)
