### ISSUE TITLE
910服务器linux系统安装lmdb和lanms库报错

### ISSUE THREAD

**Issue by 1257597709** [mindspore-lab/mindocr#761]
**使用pip install安装lmdb库报错：**
Collecting lmdb
Using cached lmdb-1.5.1.tar.gz (881 kB)
Preparing metadata (setup.py) ... done
Building wheels for collected packages: lmdb
Building wheel for lmdb (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [23 lines of output]
py-lmdb: Using bundled liblmdb with py-lmdb patches; override with LMDB_FORCE_SYSTEM=1 or LMDB_PURE=1.
patching file lmdb.h
patching file mdb.c
py-lmdb: Using CPython extension; override with LMDB_FORCE_CFFI=1.
running bdist_wheel
running build
running build_py
creating build/lib.linux-aarch64-cpython-39/lmdb
copying lmdb/tool.py -> build/lib.linux-aarch64-cpython-39/lmdb
copying lmdb/cffi.py -> build/lib.linux-aarch64-cpython-39/lmdb
copying lmdb/_config.py -> build/lib.linux-aarch64-cpython-39/lmdb
copying lmdb/main.py -> build/lib.linux-aarch64-cpython-39/lmdb
copying lmdb/init.py -> build/lib.linux-aarch64-cpython-39/lmdb
running build_ext
building 'cpython' extension
creating build/temp.linux-aarch64-cpython-39/build/lib
creating build/temp.linux-aarch64-cpython-39/lmdb
gcc -pthread -B /opt/conda/conda-bld/python-split_1648580438111/h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -n1 .2-a+fp16+rcpc+dotprod+crypto -isystem /opt/conda/conda-bld/python-split_1648580438111/h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -I/opt/conda/conda-bld/python-split_1648580438111/h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -fPIC -O2 -n1 .2-a+fp16+rcpc+dotprod+crypto -isystem /opt/conda/conda-bld/python-split_1648580438111/h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -fPIC -Ilib/py-lmdb -Ibuild/lib -I/home/ic314/miniconda3/envs/mindspore2.3_py39/include/python3.9 -c build/lib/mdb.c -o build/temp.linux-aarch64-cpython-39/build/lib/mdb.o -DHAVE_PATCHED_LMDB=1 -UNDEBUG -w
gcc: 错误：.2-a+fp16+rcpc+dotprod+crypto：没有那个文件或目录
gcc: 错误：.2-a+fp16+rcpc+dotprod+crypto：没有那个文件或目录
gcc: 错误：unrecognized command line option ‘-n1’; did you mean ‘-n’?
gcc: 错误：unrecognized command line option ‘-n1’; did you mean ‘-n’?
error: command '/usr/bin/gcc' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for lmdb
Running setup.py clean for lmdb
Failed to build lmdb
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (lmdb)

**pip install安装lanms报错：**
Collecting lanms>=1.0.2 (from -r requirements.txt (line 16))
Using cached lanms-1.0.2.tar.gz (973 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [14 lines of output]
make: 进入目录“/tmp/pip-install-2j1qeakl/lanms_9d340ec13daa4acf8e6413ce0fb43013”
g++ -o lanms/adaptor.so -I include -std=c++11 -O3 -I/home/ic314/miniconda3/envs/mindspore2.3_py39/include/python3.9 -I/home/ic314/miniconda3/envs/mindspore2.3_py39/include/python3.9 -Wno-unused-result -Wsign-compare -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -mtune=neoverse-n1 -march=armv8.2-a+fp16+rcpc+dotprod+crypto -isystem /home/ic314/miniconda3/envs/mindspore2.3_py39/include -fdebug-prefix-map=/opt/conda/conda-bld/python-split_1648580438111/work=/usr/local/src/conda/python-3.9.11 -fdebug-prefix-map=/opt/conda/conda-bld/python-split_1648580438111/h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold=/usr/local/src/conda-prefix -I/opt/conda/conda-bld/python-split_1648580438111/h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -DNDEBUG -O3 -Wall -L/home/ic314/miniconda3/envs/mindspore2.3_py39/lib/python3.9/config-3.9-aarch64-linux-gnu -L/home/ic314/miniconda3/envs/mindspore2.3_py39/lib -lcrypt -lpthread -ldl -lutil -lm -lm adaptor.cpp include/clipper/clipper.cpp --shared -fPIC
cc1plus: 错误：invalid feature modifier in ‘-march=armv8.2-a+fp16+rcpc+dotprod+crypto’
cc1plus: 错误：-mtune 参数的值 ‘neoverse-n1’ 未知
cc1plus: 错误：invalid feature modifier in ‘-march=armv8.2-a+fp16+rcpc+dotprod+crypto’
cc1plus: 错误：-mtune 参数的值 ‘neoverse-n1’ 未知
make: *** [Makefile:10：lanms/adaptor.so] 错误 1
make: 离开目录“/tmp/pip-install-2j1qeakl/lanms_9d340ec13daa4acf8e6413ce0fb43013”
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "/tmp/pip-install-2j1qeakl/lanms_9d340ec13daa4acf8e6413ce0fb43013/setup.py", line 28, in
raise RuntimeError('Cannot compile lanms in the directory: {}'.format(BASE_DIR))
RuntimeError: Cannot compile lanms in the directory: /tmp/pip-install-2j1qeakl/lanms_9d340ec13daa4acf8e6413ce0fb43013
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by alien-0119** [comment]
您好，这个问题现象与conda的一个bug导致的现象十分相似：https://github.com/ContinuumIO/anaconda-issues/issues/13106

您可以选择使用python 3.8或升级conda版本解决这个问题。

希望以上信息可以对您有所帮助。

**Comment by 1257597709** [comment]
您好，感谢回复，目前我使用的python版本是3.9.11，再更改python版本为3.8后，即可正常安装了
