### ISSUE TITLE
需要在readme写清楚mindocr 依赖的python 版本

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindocr#99]
(model_zoo_r2.0.0) root@10-90-53-131:test_mindocr# pip install mindocr-0.0.1-py3-none-any.whl
Looking in indexes: http://cmc-cd-mirror.rnd.huawei.com/pypi/simple/
Processing ./mindocr-0.0.1-py3-none-any.whl
Requirement already satisfied: numpy>=1.17.0 in /data1/archiconda3/envs/model_zoo_r2.0.0/lib/python3.7/site-packages (from mindocr==0.0.1) (1.21.6)
ERROR: Package 'mindocr' requires a different Python: 3.7.5 not in '>=3.9'

**Comment by HaoyangLee** [comment]
已说明。PR #167

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
